#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Glib-Object-Introspection
Version  : 0.047
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/X/XA/XAOC/Glib-Object-Introspection-0.047.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/X/XA/XAOC/Glib-Object-Introspection-0.047.tar.gz
Summary  : 'Dynamically create Perl language bindings'
Group    : Development/Tools
License  : LGPL-2.1
Requires: perl-Glib-Object-Introspection-bin = %{version}-%{release}
Requires: perl-Glib-Object-Introspection-lib = %{version}-%{release}
Requires: perl-Glib-Object-Introspection-license = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(ExtUtils::Depends)
BuildRequires : perl(ExtUtils::PkgConfig)
BuildRequires : perl(Glib)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(gobject-introspection-1.0)

%description
Glib::Object::Introspection
===========================
Glib::Object::Introspection uses the gobject-introspection and libffi projects
to dynamically create Perl bindings for a wide variety of libraries.  Examples
include gtk+, webkit, libsoup and many more.

%package bin
Summary: bin components for the perl-Glib-Object-Introspection package.
Group: Binaries
Requires: perl-Glib-Object-Introspection-license = %{version}-%{release}

%description bin
bin components for the perl-Glib-Object-Introspection package.


%package dev
Summary: dev components for the perl-Glib-Object-Introspection package.
Group: Development
Requires: perl-Glib-Object-Introspection-lib = %{version}-%{release}
Requires: perl-Glib-Object-Introspection-bin = %{version}-%{release}
Provides: perl-Glib-Object-Introspection-devel = %{version}-%{release}
Requires: perl-Glib-Object-Introspection = %{version}-%{release}

%description dev
dev components for the perl-Glib-Object-Introspection package.


%package lib
Summary: lib components for the perl-Glib-Object-Introspection package.
Group: Libraries
Requires: perl-Glib-Object-Introspection-license = %{version}-%{release}

%description lib
lib components for the perl-Glib-Object-Introspection package.


%package license
Summary: license components for the perl-Glib-Object-Introspection package.
Group: Default

%description license
license components for the perl-Glib-Object-Introspection package.


%prep
%setup -q -n Glib-Object-Introspection-0.047

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Glib-Object-Introspection
cp LICENSE %{buildroot}/usr/share/package-licenses/perl-Glib-Object-Introspection/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/Glib/Object/Introspection.pm
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/Glib/Object/Introspection/Install/Files.pm

%files bin
%defattr(-,root,root,-)
/usr/bin/perli11ndoc

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Glib::Object::Introspection.3

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/auto/Glib/Object/Introspection/Introspection.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Glib-Object-Introspection/LICENSE
